language: python
python:
- 3.5
- 3.8
env:
- TOXENV=django22
- TOXENV=quality
- TOXENV=pii-annotations
matrix:
  include:
  - python: 3.8
    env: TOXENV=django30
cache:
- pip
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = quality"
  password:
    secure: hSTBA1mxhBELsq5FET07JjhjtrrjQiSupf6oe29xXvHaBXFPkKs0991hu9ykA2AeaZNmloZRbUb6B63tULz5+ud7LlJtJTbq12JKJAqstzTkvoH9vE4x1Jq5JVQjeCBJtcEVO0/3ipCQoDE8SKwFwgGv1t74O1qzeTIgOg9IRy5D1lp9udSoGdmWvmxAxww4zV1frgO2UZdQVVyJt2QiuCa7lLx8r5gHq4PXD9wgLdbbFpXvyZQov4YhoDGQKLccoSW3sZB5CHcOOBoOIueW1rdkZbvtz9RsdpSHt8ImD85IRlEURtwqRlqtxqiTLZ328SV5c5Cpc5vsPYBHfmpVe+78uybzmK9qsurou6G6uO44fX+ORrk3CYpayUEGQdPovUi87dUhizFBTGytdR6mJ8+msAL+j6XTQ3GqppuUOmUoG/FikXy5TR5UpP99HIBaG2WaqiPIyUxNqRrYAzABo9CR4oARSeKXoVq1FVvxP0S/+O5Rz9lPVjcywINSzbj8VxNrmBPMM8ZdsztMzXVSKmCOyKwaBd/cYgYgYrrvf8oveyrGuJRYCOSOQOiiwnjKRGTMNQ+JibKfnhFYtqbprEeOLEQb8Yx8jMSoZtMlwHLWBSyx985N7qTnUAqUoZ2HcUI1iRqCk683KzcCNgNZlCqBNeHJZnOqcx9Uj3ShuWc=
